version:  '3.7'

services: 
    web:
        build: .
        ports:
            - '8080:8080'
        volumes: 
            - ./:/app
        command: >
            bash -c "cd app && python app/app.py" 
