version:  '3.7'

services: 
#    web:
#        build: .
#        ports:
#            - '8080:8080'
#        volumes: 
#            - ./:/app
#        depends_on:
#            - redis
#        command: >
#            bash -c "cd app && python app/app.py" 
    redis:
        restart: always
        image: redis:6.0.3
        ports:
            - "6379:6379"
        expose:
            - "6379"
        volumes:
            - redis_data:/data
        env_file:
            - .env

volumes:
    redis_data:
